name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-cmake-msvc:

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7
      with:
        ref: 'v19.7.0-ci'
        
    - name: cmake
      run: cmake . -DPA_USE_DS=OFF -DPA_USE_JACK=OFF -DPA_USE_WASAPI=OFF -DPA_USE_WDMKS=ON -DPA_USE_WDMKS_DEVICE_INFO=ON -DPA_USE_WMME=OFF
      
    - name: build
      run: cmake --build .

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: portaudio-Windows-artifact
        path: ${{github.workspace}}
        if-no-files-found: ignore
        retention-days: 0
